# Generated by Django 3.1.1 on 2020-09-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=100)),
                ('muscleGroupOne', models.CharField(max_length=200)),
                ('muscleGroupTwo', models.CharField(max_length=200)),
                ('muscleGroupThree', models.CharField(max_length=200)),
                ('levelOfDifficulty', models.CharField(max_length=100)),
                ('workout_img', models.TextField()),
                ('workout_url', models.TextField()),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
